[package]
name = "cisco_decrypt"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Simple tool to decrypt Cisco Type 7 passwords"
repository = "https://github.com/richardstrnad/cisco_decrypt"

[dependencies]
